apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "translator.name" . }}-ui
  labels:
    app.kubernetes.io/component: ui
    {{- include "translator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
      {{- include "translator.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ui
        {{- include "translator.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: {{ .Values.image.ui }}
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: {{ include "translator.name" . }}-env
