{{- if and .Values.secret.create .Values.secret.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "translator.name" . }}-hf
  labels:
    {{- include "translator.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUGGINGFACE_TOKEN: {{ .Values.secret.hfToken | quote }}
{{- end }}
