apiVersion: v1
kind: Service
metadata:
  name: {{ include "translator.name" . }}-ui
  labels:
    {{- include "translator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: ui
    {{- include "translator.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8501