apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-ui
  namespace: translator
spec:
  replicas: 1
  selector:
    matchLabels: { app: translator-ui }
  template:
    metadata:
      labels: { app: translator-ui }
    spec:
      containers:
        - name: ui
          image: translator-ui:0.1
          ports: [{ containerPort: 8501 }]
          envFrom:
            - configMapRef: { name: translator-env }
